app:
  image: node
  volumes:
    - .:/usr/src/app
  links:
    - rtdb
  environment:
    NODE_ENV: development
    MINT_USER:
    MINT_PASSWORD:
  command: bash

rtdb:
  image: rethinkdb
  environment:
    VIRTUAL_HOST: rt.docker
  ports:
    - "28015"
    - "29015"
    - "8088:8080"

